### PR TITLE
Fix typo in 01-silverblue-nix.md

### PR DESCRIPTION
**Pull request by rohanssrao**

### CODE REVIEW

**Comment by osalbahr** [comment]
Strangely enough, `nix` worked fine (so far) even with this typo.

**Review by Hofer-Julian — APPROVED** [review]
Thank you!

**Comment by osalbahr** [comment]
@Hofer-Julian FYI it looks like the CI to re-build the website failed: https://github.com/Hofer-Julian/julianhofer.eu/actions/runs/5450993548/jobs/9916809255

**Comment by Hofer-Julian** [comment]
Thanks @osalbahr, I had to tweak the CI a bit to work again :)

**Pull request merged**
